require('dotenv').config()
const express = require('express')
const cors = require('cors')
const { connectBD } = require('./src/config/db.js')
const cuadroRouters = require('./src/api/routes/cuadro.js')
const app = express()
connectBD()
app.use(express.json())
app.use(cors())
app.use('/api/v1/productos', cuadroRouters)
app.use('*', (req, res, next) => res.status(404).json('rute not  found'))
app.listen(3000, () => {
  console.log('http://localhost:3000')
})
